# Teacher-Tester System Configuration

# Model settings
models:
  teacher:
    base_model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1024
    top_p: 0.95
  tester:
    base_model: "gpt-3.5-turbo"
    temperature: 0.8  # Slightly higher for more natural responses
    max_tokens: 1024
    top_p: 0.95

# Conversation settings
conversation:
  confidence_threshold: 0.8
  max_exchanges: 5
  rating_range:
    min: 0.0
    max: 10.0
  initial_prompts:
    python_programming: "Let's discuss Python programming concepts. I'd like to understand your knowledge level in this area."
    machine_learning: "I'd like to explore your understanding of machine learning concepts and techniques."
    data_science: "Let's talk about data science. I'm interested in understanding your knowledge in this field."
    web_development: "I'd like to discuss web development technologies and practices with you."

# Data storage
storage:
  conversations_dir: "data/conversations"
  training_examples_dir: "data/training"
  file_format: "json"
  
# Logging
logging:
  level: "INFO"
  file: "logs/teacher_tester.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Evaluation
evaluation:
  metrics:
    - "mean_absolute_error"
    - "confidence_calibration"
    - "conversation_length"
  
# Development settings
development:
  simulate_api: true
  verbose_logging: true