# Teacher-Tester System Configuration

# Model settings
models:
  path: "C:/Users/charl/Documents/AI/Diss/Quinn 1.5B attempt/DeepSeek-R1-Distill-Qwen-1.5B"  # Absolute path with forward slashes
  teacher:
    base_model: "local-deepseek"  # Identifier for the model used by the teacher
    temperature: 0.7
    max_tokens: 512  # Match BasicChatbot.py
    top_p: 0.9  # Match BasicChatbot.py
  tester:
    base_model: "local-deepseek"  # Identifier for the model used by the tester
    temperature: 0.8  # Slightly higher for more natural responses
    max_tokens: 512  # Match BasicChatbot.py
    top_p: 0.9  # Match BasicChatbot.py

# Conversation settings
conversation:
  confidence_threshold: 0.8
  max_exchanges: 5
  rating_range:
    min: 0.0
    max: 10.0
  initial_prompts:
    "Python Programming": "Let's discuss Python programming concepts. I'd like to understand your knowledge level in this area."
    "Machine Learning": "I'd like to explore your understanding of machine learning concepts and techniques."
    "Data Science": "Let's talk about data science. I'm interested in understanding your knowledge in this field."
    "Web Development": "I'd like to discuss web development technologies and practices with you."

# Data storage
storage:
  conversations_dir: "./data/conversations"  # Relative to the project directory
  training_examples_dir: "./data/training"  # Relative to the project directory
  file_format: "json"
  
# Logging
logging:
  level: "INFO"
  file: "./logs/teacher_tester.log"  # Relative to the project directory
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Evaluation
evaluation:
  metrics:
    - "mean_absolute_error"
    - "confidence_calibration"
    - "conversation_length"
  
# Development settings
development:
  simulate_api: false  # Set to false to use the local model
  verbose_logging: true
